import NotFound from "./NotFound";
import NotAuthorized from "./NotAuthorized";
import Dashboard from "./Dashboard";
import Login from "./Login";
import Home from "./Home";
import Auth from "./Auth";
import Register from "./Register"
import ManajemenData from "./ManajemenData"
import ManajemenDataInput from "./ManajemenDataInput"
import ManajemenDataInputPhase2 from "./ManajemenDataInput/phase2"
import ManajemenDataInputPhase3 from "./ManajemenDataInput/phase3"
import Simulasi from "./Simulasi"
import SimulasiMap from "./SimulasiMap"
import ConfirmByCode from "./ConfirmByCode"
import ResentEmailConfirmation from "./ResentEmailConfirmation"
import ForgotPassword from "./ForgotPassword"
import ResetPassword from "./ResetPassword"
import UserManagement from "./UserManagement"
import UserManagementEdit from "./UserManagement/edit"
import UserManagementCreate from "./UserManagement/add"
import RoleManagement from "./RoleManagement"
import RoleManagementEdit from "./RoleManagement/edit"
import RoleManagementCreate from "./RoleManagement/add"
import Profile from './Profile'
import ProfileEdit from './Profile/edit'
import Report from './Report'
import HelpManagement from './Helps/HelpManagement'
import HelpManagementCreate from './Helps/HelpManagement/add'
import HelpManagementEdit from './Helps/HelpManagement/edit'
import HelpData from './Helps/HelpData'

export { NotFound, NotAuthorized, Dashboard, Login, Home, Auth, ManajemenData, Register, ManajemenDataInput, ManajemenDataInputPhase2, ManajemenDataInputPhase3, Simulasi, SimulasiMap, ConfirmByCode, ResentEmailConfirmation, ForgotPassword, ResetPassword, UserManagement, UserManagementEdit, UserManagementCreate,RoleManagement, RoleManagementEdit, RoleManagementCreate, Profile, ProfileEdit, Report, HelpManagement, HelpManagementCreate, HelpManagementEdit, HelpData };
